-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS nerielearning.m_class
(
    m_class_id bigint NOT NULL,
    is_active boolean NOT NULL,
    m_class_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    m_class_serial_no character varying(255) COLLATE pg_catalog."default" NOT NULL,
    m_stage_id bigint,
    CONSTRAINT m_class_pkey PRIMARY KEY (m_class_id),
    CONSTRAINT uk_kqkp31plucvts2gna37wjrn8r UNIQUE (m_class_name),
    CONSTRAINT uk_mo1ew0gxuhnt3ahfk8cyotoxu UNIQUE (m_class_serial_no)
);

CREATE TABLE IF NOT EXISTS nerielearning.m_competency
(
    m_competency_id bigint NOT NULL,
    m_competency_name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT m_competency_pkey PRIMARY KEY (m_competency_id),
    CONSTRAINT uk_22hv9tgcd34jg9b5bq642rcfj UNIQUE (m_competency_name)
);

CREATE TABLE IF NOT EXISTS nerielearning.m_goal
(
    m_goal_id bigint NOT NULL,
    m_goal_name character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT m_goal_pkey PRIMARY KEY (m_goal_id),
    CONSTRAINT uk_f0kypg1ouaoadf1f5o05g3u4t UNIQUE (m_goal_name)
);

CREATE TABLE IF NOT EXISTS nerielearning.m_role
(
    role_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    landing_page character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role_name character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT m_role_pkey PRIMARY KEY (role_code)
);

CREATE TABLE IF NOT EXISTS nerielearning.m_stage
(
    m_stage_id bigint NOT NULL,
    is_active boolean NOT NULL,
    m_stage_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    m_stage_serial_no character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT m_stage_pkey PRIMARY KEY (m_stage_id),
    CONSTRAINT uk_64h14xcmw7eu7qtdqwqhku8y6 UNIQUE (m_stage_serial_no),
    CONSTRAINT uk_eofm6wgx8l2ldb9qj815ryvw8 UNIQUE (m_stage_name)
);

CREATE TABLE IF NOT EXISTS nerielearning.m_subject
(
    m_subject_id bigint NOT NULL,
    is_active boolean NOT NULL,
    m_subject_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT m_subject_pkey PRIMARY KEY (m_subject_id),
    CONSTRAINT uk_g52q3a1ij8jd4jrx1g8k76awk UNIQUE (m_subject_name)
);

CREATE TABLE IF NOT EXISTS nerielearning.map_class_subject
(
    map_class_subject_id bigint NOT NULL,
    is_active boolean NOT NULL,
    m_class_id bigint,
    m_subject_id bigint,
    CONSTRAINT map_class_subject_pkey PRIMARY KEY (map_class_subject_id)
);

CREATE TABLE IF NOT EXISTS nerielearning.t_competency
(
    t_competency_id bigint NOT NULL,
    t_competency_description character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    t_competency_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    m_competency_id bigint,
    t_goal_id bigint,
    is_active boolean NOT NULL,
    CONSTRAINT t_competency_pkey PRIMARY KEY (t_competency_id),
    CONSTRAINT uk_639u422ql149yd17pa299xpqm UNIQUE (t_competency_description),
    CONSTRAINT uk_bjdtn4433hyn5l1bnvgbtxpvv UNIQUE (t_competency_name)
);

CREATE TABLE IF NOT EXISTS nerielearning.t_goal
(
    t_goal_id bigint NOT NULL,
    is_active boolean NOT NULL,
    t_goal_description character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    t_goal_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    m_goal_id bigint,
    map_class_subject_id bigint,
    CONSTRAINT t_goal_pkey PRIMARY KEY (t_goal_id),
    CONSTRAINT uk_1dishydat1s2vfwf0fihhp4tm UNIQUE (t_goal_name),
    CONSTRAINT uk_7mfscnd2w1dh9oh5oqsbui5vd UNIQUE (t_goal_description)
);

CREATE TABLE IF NOT EXISTS nerielearning.t_losa
(
    t_lo_sa_id bigint NOT NULL,
    learning_outcome character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    suggestive_activity character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    t_competency_id bigint,
    is_active boolean NOT NULL,
    CONSTRAINT t_losa_pkey PRIMARY KEY (t_lo_sa_id),
    CONSTRAINT uk_58q2eimi2mgn8yg6ukc511jxb UNIQUE (suggestive_activity),
    CONSTRAINT uk_cwk5n05x28s0ultrkc0aj0tri UNIQUE (learning_outcome)
);

CREATE TABLE IF NOT EXISTS nerielearning.t_userlogin
(
    user_login_id bigint NOT NULL DEFAULT nextval('nerielearning.t_userlogin_user_login_id_seq'::regclass),
    entrydate timestamp(6) without time zone NOT NULL,
    is_active boolean NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    role_id character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT t_userlogin_pkey PRIMARY KEY (user_login_id),
    CONSTRAINT uk_bad44gsit802dr52l08y1a9cl UNIQUE (username),
    CONSTRAINT uk_r2pvv8h5hgsru30xsi1r70ola UNIQUE (role_id)
);

ALTER TABLE IF EXISTS nerielearning.m_class
    ADD CONSTRAINT fknunfcjxbj3bt0618ld20echdl FOREIGN KEY (m_stage_id)
    REFERENCES nerielearning.m_stage (m_stage_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.map_class_subject
    ADD CONSTRAINT fkclvjgvj4e20rxvkslrs86mx1b FOREIGN KEY (m_class_id)
    REFERENCES nerielearning.m_class (m_class_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.map_class_subject
    ADD CONSTRAINT fkjsdvvufvt3arap0c6n5sv4ovj FOREIGN KEY (m_subject_id)
    REFERENCES nerielearning.m_subject (m_subject_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.t_competency
    ADD CONSTRAINT fke8ir74ldj1375usssuykf9agj FOREIGN KEY (t_goal_id)
    REFERENCES nerielearning.t_goal (t_goal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.t_competency
    ADD CONSTRAINT fkm974s9gfqur8kdagbkgnuolu5 FOREIGN KEY (m_competency_id)
    REFERENCES nerielearning.m_competency (m_competency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.t_goal
    ADD CONSTRAINT fki2fw8aqqjkhtjgsphniiya9r3 FOREIGN KEY (m_goal_id)
    REFERENCES nerielearning.m_goal (m_goal_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.t_goal
    ADD CONSTRAINT fklmcqwpd4tx4dl35kvxntar0x FOREIGN KEY (map_class_subject_id)
    REFERENCES nerielearning.map_class_subject (map_class_subject_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.t_losa
    ADD CONSTRAINT fkaa89yeu5q403tv7v3n2mr5gv FOREIGN KEY (t_competency_id)
    REFERENCES nerielearning.t_competency (t_competency_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS nerielearning.t_userlogin
    ADD CONSTRAINT fklpeqw2tlvj01959u55wlmkxap FOREIGN KEY (role_id)
    REFERENCES nerielearning.m_role (role_code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk_r2pvv8h5hgsru30xsi1r70ola
    ON nerielearning.t_userlogin(role_id);

END;